/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugas;

/**
 *
 * @author YeniNAzizah
 */
public class FrameTugas extends javax.swing.JFrame {

    /**
     * Creates new form FrameTugas
     */
    public FrameTugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hb1 = new javax.swing.JLabel();
        hb2 = new javax.swing.JLabel();
        hb3 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        brg1 = new javax.swing.JTextField();
        brg2 = new javax.swing.JTextField();
        brg3 = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dskn.setText("Diskon");
        getContentPane().add(dskn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 10));

        jLabel2.setText("Pembayaran");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        hb1.setText("Harga Barang 1");
        getContentPane().add(hb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        hb2.setText("Harga Barang 2");
        getContentPane().add(hb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        hb3.setText("Harga Barang 3");
        getContentPane().add(hb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        getContentPane().add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 30));

        brg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg1ActionPerformed(evt);
            }
        });
        getContentPane().add(brg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, 30));

        brg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg2ActionPerformed(evt);
            }
        });
        getContentPane().add(brg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 30));

        brg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg3ActionPerformed(evt);
            }
        });
        getContentPane().add(brg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, 30));

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 310, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed

    private void brg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg1ActionPerformed

    private void brg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg2ActionPerformed

    private void brg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg3ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int barang1 = Integer.parseInt(brg1.getText());
        int barang2 = Integer.parseInt(brg2.getText());
        int barang3 = Integer.parseInt(brg3.getText());
        
        int total = barang1+barang2+barang3;
        int diskon = Integer.parseInt(dis.getText());
        int diskonn =total*diskon/100;
        int bayar = total-diskonn;
        
        hasil.setText("\nHarga Barang 1 :"+barang1+"\nHarga Barang 2 :"+barang2+"\nHarga Barang 3 :"+barang3+"\nTotal Harga :"+total+"\nDiskon :"+diskon+"\nTotal Pembayaran :"+bayar);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField dis;
    private javax.swing.JLabel dskn;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel hb1;
    private javax.swing.JLabel hb2;
    private javax.swing.JLabel hb3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
